export type ErrorReason = 'UNAUTHORIZED' | 'TOKEN_MISSING' | 'TOKEN_INVALID' | 'TOKEN_EXPIRED' | 'FORBIDDEN' | 'PERMISSION_DENIED' | 'CHANNEL_MANAGE_FORBIDDEN' | 'EMAIL_ALREADY_REGISTERED' | 'USER_ALREADY_MEMBER' | 'INVITE_ALREADY_PENDING' | 'CANNOT_EDIT_OWNER' | 'CANNOT_REMOVE_OWNER' | 'CANNOT_REMOVE_SELF' | 'COLLABORATOR_LIMIT_REACHED' | 'EMAIL_ALREADY_EXISTS' | 'INVALID_CREDENTIALS' | 'USER_NOT_FOUND' | 'USER_WITHOUT_WORKSPACE' | 'NOT_FOUND' | 'VALIDATION_ERROR' | 'INTERNAL_ERROR' | 'CHANNEL_NOT_FOUND' | 'CHANNEL_NOT_CONNECTED' | 'CHANNEL_PROVIDER_MISMATCH' | 'CHANNEL_MISSING_CREDENTIALS' | 'CHANNEL_DELETE_FAILED' | 'CHANNEL_NOT_INSTAGRAM' | 'INSTAGRAM_TOKEN_EXPIRED' | 'INSTAGRAM_SEND_FAILED' | 'INSTAGRAM_OPTIN_SEND_FAILED' | 'INSTAGRAM_CONVERSATIONS_FAILED' | 'INSTAGRAM_MEDIA_FAILED' | 'INSTAGRAM_SYNC_FAILED' | 'INSTAGRAM_CONNECT_FAILED' | 'INSTAGRAM_OAUTH_MISSING_PARAMS' | 'INSTAGRAM_INSTANCE_LIMIT_EXCEEDED' | 'INSTANCE_LIMIT_EXCEEDED' | 'RECURRING_NOTIFICATION_TOKEN_INVALID' | 'RECURRING_NOTIFICATION_TOKEN_EXPIRED' | 'NO_RECURRING_OPTIN' | 'WHATSAPP_ENV_MISSING' | 'WHATSAPP_CONNECT_FAILED' | 'WHATSAPP_STATUS_FAILED' | 'WHATSAPP_QR_FAILED' | 'WHATSAPP_DISCONNECT_FAILED' | 'WHATSAPP_WEBHOOK_CONFIG_FAILED' | 'WHATSAPP_SEND_FAILED' | 'WHATSAPP_DELETE_MSG_FAILED' | 'WHATSAPP_MARK_READ_FAILED' | 'WHATSAPP_LIST_CONTACTS_FAILED' | 'WHATSAPP_LIST_GROUPS_FAILED' | 'WHATSAPP_SYNC_FAILED' | 'WHATSAPP_INSTANCE_LIMIT_EXCEEDED' | 'CONTACT_NOT_FOUND' | 'CONTACT_IDENTITY_MISSING' | 'CONTACT_INVALID_PHONE' | 'CONTACT_SEND_FAILED' | 'GROUP_NOT_FOUND' | 'GROUP_NOT_MANUAL' | 'GROUP_CONTACTS_LIMIT_EXCEEDED' | 'CAMPAIGN_NOT_FOUND' | 'CAMPAIGN_NO_CONTACTS' | 'CAMPAIGN_RUN_FAILED' | 'CAMPAIGN_LIMIT_EXCEEDED' | 'CAMPAIGN_CONTACTS_LIMIT_EXCEEDED' | 'AUTO_REPLY_NOT_FOUND' | 'AUTO_REPLY_CREATE_FAILED' | 'AUTO_REPLY_UPDATE_FAILED' | 'AUTO_REPLY_DELETE_FAILED' | 'AUTO_REPLY_TOGGLE_FAILED' | 'AUTO_REPLY_LIMIT_EXCEEDED' | 'AUTO_REPLY_KEYWORD_REQUIRED' | 'COMMENT_AUTOMATION_LIMIT_EXCEEDED' | 'AI_CHANNEL_LIMIT_EXCEEDED' | 'AI_PLAN_REQUIRED' | 'AI_CHANNEL_IN_OTHER_PROFILE' | 'AI_PROFILE_LIMIT_EXCEEDED' | 'AI_PROFILE_NOT_FOUND' | 'AI_PROFILE_LAST_ONE' | 'CUSTOM_RULES_LIMIT_EXCEEDED' | 'SCHEDULING_QUERY_NOT_ALLOWED' | 'SCHEDULING_BOOKING_NOT_ALLOWED' | 'WEBHOOK_SIGNATURE_INVALID' | 'WEBHOOK_VERIFICATION_FAILED' | 'NETWORK_ERROR' | 'UNKNOWN' | 'WA_OFFICIAL_NOT_CONFIGURED' | 'WA_SIGNUP_CODE_EXCHANGE_FAILED' | 'WA_WABA_NOT_FOUND' | 'WA_WEBHOOK_SUBSCRIBE_FAILED' | 'WA_PHONE_NUMBERS_FAILED' | 'WA_NO_PHONE_NUMBERS' | 'WA_PHONE_NUMBER_NOT_FOUND' | 'WA_CHANNEL_ALREADY_CONNECTED' | 'WA_PHONE_IN_USE_BY_OTHER_WORKSPACE' | 'WA_HEALTH_SYNC_FAILED' | 'WA_OUTSIDE_SERVICE_WINDOW' | 'WA_TEMPLATE_NOT_FOUND' | 'WA_TEMPLATE_NOT_APPROVED' | 'WA_TEMPLATE_ALREADY_EXISTS' | 'WA_TEMPLATE_INVALID_NAME' | 'WA_TEMPLATE_NOT_EDITABLE' | 'WA_TEMPLATE_NOT_SYNCED' | 'WA_TEMPLATE_CREATE_FAILED' | 'WA_TEMPLATE_UPDATE_FAILED' | 'WA_TEMPLATE_HEADER_UPLOAD_FAILED' | 'WA_TEMPLATE_REQUIRED_FOR_OFFICIAL' | 'WA_TEMPLATE_ONLY_FOR_OFFICIAL_CHANNELS' | 'WA_TEMPLATE_CHANNEL_MISMATCH' | 'CAMPAIGN_MIXED_CHANNEL_TYPES' | 'WA_MARKETING_OPT_OUT' | 'WA_MARKETING_LIMIT_REACHED' | 'WA_BILLING_ISSUE' | 'WA_RATE_LIMITED' | 'CONTACT_WITHOUT_PHONE' | 'RECIPIENT_REQUIRED' | 'INVALID_PHONE' | 'PRODUCT_LIMIT_EXCEEDED' | 'PRODUCT_NOT_FOUND' | 'IMPORT_FILE_EMPTY' | 'IMPORT_FILE_TOO_LARGE' | 'IMPORT_FILE_NOT_XLSX' | 'IMPORT_FILE_LEGACY_XLS' | 'IMPORT_FILE_CORRUPTED' | 'IMPORT_FILE_UNREADABLE' | 'IMPORT_SHEET_NOT_FOUND' | 'IMPORT_NAME_COLUMN_NOT_FOUND' | 'IMPORT_PHONE_COLUMN_NOT_FOUND' | 'CONTACT_LIMIT_EXCEEDED' | 'PRODUCTS_WITHOUT_IMAGE' | 'IMAGE_TOO_LARGE' | 'INVALID_IMAGE' | 'AUTOMATION_DRAFT_FAILED' | 'AUTOMATION_DRAFT_RATE_LIMITED' |'AI_SIMULATION_NEEDS_CUSTOMER_MESSAGE' | 'AI_SIMULATION_UNAVAILABLE' | 'AI_SIMULATION_RATE_LIMITED' | 'NO_SUBSCRIPTION' | 'SUBSCRIPTION_INACTIVE' | 'CART_RECOVERY_INTEGRATION_LIMIT_EXCEEDED' | 'CHANNEL_TYPE_MISMATCH' | 'INTEGRATION_NOT_FOUND' | 'CART_NOT_FOUND';
export const ERROR_MESSAGES: Record<ErrorReason, string> = {
  UNAUTHORIZED: 'Sua sessão expirou. Entre de novo para continuar.',
  TOKEN_MISSING: 'Sua sessão expirou. Entre de novo para continuar.',
  TOKEN_INVALID: 'Não conseguimos confirmar o seu acesso. Entre de novo para continuar.',
  TOKEN_EXPIRED: 'Sua sessão expirou. Entre de novo para continuar.',
  FORBIDDEN: 'Você não tem permissão para fazer isso. Peça ao administrador da conta para liberar.',
  PERMISSION_DENIED: 'Você não tem permissão para acessar esta área. Peça ao administrador da conta para liberar.',
  CHANNEL_MANAGE_FORBIDDEN: 'Esta conexão foi feita por outra pessoa. Só quem conectou ou o administrador da conta pode alterá-la.',
  EMAIL_ALREADY_REGISTERED: 'Este e-mail já tem uma conta no Synq. Peça ao administrador um convite para outro e-mail.',
  USER_ALREADY_MEMBER: 'Esta pessoa já faz parte da sua equipe.',
  INVITE_ALREADY_PENDING: 'Já existe um convite esperando resposta para este e-mail. Peça para a pessoa olhar a caixa de entrada.',
  CANNOT_EDIT_OWNER: 'As permissões do administrador da conta não podem ser alteradas.',
  CANNOT_REMOVE_OWNER: 'O administrador da conta não pode ser removido por aqui.',
  CANNOT_REMOVE_SELF: 'Você não pode remover a sua própria conta por aqui.',
  COLLABORATOR_LIMIT_REACHED: 'Seu plano chegou ao limite de colaboradores. Mude de plano para convidar mais pessoas.',
  EMAIL_ALREADY_EXISTS: 'Este e-mail já está cadastrado. Entre com ele ou use a opção "Esqueci minha senha".',
  INVALID_CREDENTIALS: 'E-mail ou senha incorretos. Confira os dados e tente de novo.',
  USER_NOT_FOUND: 'Não encontramos a sua conta. Entre de novo ou fale com o suporte.',
  USER_WITHOUT_WORKSPACE: 'Sua conta não está ligada a nenhuma empresa. Fale com o suporte para resolver.',
  NOT_FOUND: 'Não encontramos o que você procurava. Pode ter sido excluído. Atualize a página e tente de novo.',
  VALIDATION_ERROR: 'Alguns campos estão vazios ou com erro. Confira e tente de novo.',
  INTERNAL_ERROR: 'Algo deu errado do nosso lado. Tente de novo em alguns minutos.',
  CHANNEL_NOT_FOUND: 'Não encontramos esta conexão. Ela pode ter sido removida. Atualize a página e tente de novo.',
  CHANNEL_NOT_CONNECTED: 'Este número ou conta está desconectado. Vá em Canais e conecte de novo para continuar.',
  CHANNEL_PROVIDER_MISMATCH: 'Esta ação não funciona com este tipo de conexão. Escolha outro número ou conta.',
  CHANNEL_MISSING_CREDENTIALS: 'Esta conexão está incompleta. Vá em Canais e conecte o número ou a conta de novo.',
  CHANNEL_DELETE_FAILED: 'Não foi possível remover esta conexão. Tente de novo em alguns instantes.',
  CHANNEL_NOT_INSTAGRAM: 'Este recurso só funciona com contas do Instagram. Escolha uma conta do Instagram.',
  INSTAGRAM_TOKEN_EXPIRED: 'A conexão com o Instagram expirou. Vá em Canais e conecte a conta de novo.',
  INSTAGRAM_SEND_FAILED: 'Não foi possível enviar a mensagem pelo Instagram. Tente de novo em alguns instantes.',
  INSTAGRAM_OPTIN_SEND_FAILED: 'Não foi possível pedir a autorização do contato para receber avisos. Tente de novo em alguns instantes.',
  INSTAGRAM_CONVERSATIONS_FAILED: 'Não foi possível carregar as conversas do Instagram. Atualize a página e tente de novo.',
  INSTAGRAM_SYNC_FAILED: 'Não foi possível trazer os contatos do Instagram. Tente de novo em alguns instantes.',
  INSTAGRAM_CONNECT_FAILED: 'Não foi possível conectar a conta do Instagram. Tente de novo e aceite todas as permissões pedidas.',
  INSTAGRAM_OAUTH_MISSING_PARAMS: 'A conexão com o Instagram não foi concluída. Comece de novo pelo botão de conectar.',
  INSTAGRAM_INSTANCE_LIMIT_EXCEEDED: 'Você chegou ao limite de contas do Instagram do seu plano. Remova uma conta para conectar outra.',
  INSTANCE_LIMIT_EXCEEDED: 'Você chegou ao limite de conexões do seu plano, somando WhatsApp e Instagram. Remova uma conexão ou contrate uma conexão extra em Configurações > Faturamento.',
  RECURRING_NOTIFICATION_TOKEN_INVALID: 'A autorização deste contato para receber avisos não vale mais. Peça uma nova autorização.',
  RECURRING_NOTIFICATION_TOKEN_EXPIRED: 'A autorização deste contato para receber avisos expirou. Peça uma nova autorização.',
  NO_RECURRING_OPTIN: 'Este contato ainda não autorizou receber avisos. Peça a autorização antes de enviar.',
  WHATSAPP_ENV_MISSING: 'O WhatsApp está indisponível no momento. Fale com o suporte.',
  WHATSAPP_CONNECT_FAILED: 'Não foi possível conectar o WhatsApp. Tente de novo em alguns instantes.',
  WHATSAPP_STATUS_FAILED: 'Não foi possível verificar se o WhatsApp está conectado. Atualize a página e tente de novo.',
  WHATSAPP_QR_FAILED: 'Não foi possível gerar o QR Code. Feche a janela e tente de novo.',
  WHATSAPP_DISCONNECT_FAILED: 'Não foi possível desconectar o WhatsApp. Tente de novo em alguns instantes.',
  WHATSAPP_WEBHOOK_CONFIG_FAILED: 'O WhatsApp foi conectado, mas não conseguimos ligar o recebimento de mensagens. Desconecte e conecte de novo.',
  WHATSAPP_SEND_FAILED: 'Não foi possível enviar a mensagem pelo WhatsApp. Confira se o número está conectado e tente de novo.',
  WHATSAPP_DELETE_MSG_FAILED: 'Não foi possível apagar a mensagem no WhatsApp. Tente de novo.',
  WHATSAPP_MARK_READ_FAILED: 'Não foi possível marcar a conversa como lida. Tente de novo.',
  WHATSAPP_LIST_CONTACTS_FAILED: 'Não foi possível carregar os contatos do WhatsApp. Confira se o número está conectado e tente de novo.',
  WHATSAPP_LIST_GROUPS_FAILED: 'Não foi possível carregar os grupos do WhatsApp. Confira se o número está conectado e tente de novo.',
  WHATSAPP_SYNC_FAILED: 'Não foi possível trazer os contatos do WhatsApp. Confira se o número está conectado e tente de novo.',
  WHATSAPP_INSTANCE_LIMIT_EXCEEDED: 'Você chegou ao limite de números de WhatsApp do seu plano. Remova um número para conectar outro.',
  CONTACT_NOT_FOUND: 'Não encontramos este contato. Ele pode ter sido excluído.',
  CONTACT_IDENTITY_MISSING: 'Este contato ainda não conversou por este número ou conta. Escolha outra conexão para falar com ele.',
  CONTACT_INVALID_PHONE: 'O telefone deste contato está incorreto. Corrija o número com DDD e tente de novo.',
  CONTACT_SEND_FAILED: 'Não foi possível enviar a mensagem para este contato. Tente de novo em alguns instantes.',
  GROUP_NOT_FOUND: 'Não encontramos este grupo. Ele pode ter sido excluído.',
  GROUP_NOT_MANUAL: 'Os contatos deste grupo são escolhidos automaticamente e não podem ser alterados à mão.',
  GROUP_CONTACTS_LIMIT_EXCEEDED: 'Um grupo pode ter no máximo 250 contatos. Divida os contatos em mais de um grupo.',
  CAMPAIGN_NOT_FOUND: 'Não encontramos esta campanha. Ela pode ter sido excluída.',
  CAMPAIGN_NO_CONTACTS: 'Esta campanha ainda não tem destinatários. Escolha os contatos ou um grupo antes de enviar.',
  CAMPAIGN_RUN_FAILED: 'Não foi possível iniciar a campanha. Tente de novo em alguns instantes.',
  CAMPAIGN_LIMIT_EXCEEDED: 'Você chegou ao limite de campanhas do seu plano. Exclua uma campanha antiga ou mude de plano para criar outra.',
  CAMPAIGN_CONTACTS_LIMIT_EXCEEDED: 'Uma campanha pode ter no máximo 250 contatos. Divida o envio em mais de uma campanha.',
  AUTO_REPLY_NOT_FOUND: 'Não encontramos esta automação. Ela pode ter sido excluída.',
  AUTO_REPLY_CREATE_FAILED: 'Não foi possível criar a automação. Tente de novo em alguns instantes.',
  AUTO_REPLY_UPDATE_FAILED: 'Não foi possível salvar as mudanças da automação. Tente de novo.',
  AUTO_REPLY_DELETE_FAILED: 'Não foi possível excluir a automação. Tente de novo.',
  AUTO_REPLY_TOGGLE_FAILED: 'Não foi possível ligar ou desligar a automação. Tente de novo.',
  AUTO_REPLY_KEYWORD_REQUIRED: 'Informe pelo menos uma palavra que faz a automação responder.',
  INSTAGRAM_MEDIA_FAILED: 'Não foi possível carregar as publicações do Instagram. Tente de novo em alguns instantes.',
  AUTO_REPLY_LIMIT_EXCEEDED: 'Você chegou ao limite de automações do seu plano. Exclua uma automação ou mude de plano para criar outra.',
  COMMENT_AUTOMATION_LIMIT_EXCEEDED: 'Você chegou ao limite de automações de comentários do seu plano. Exclua uma delas ou mude de plano para criar outra.',
  IMPORT_PHONE_COLUMN_NOT_FOUND: 'Não encontramos a coluna de telefone. A planilha precisa ter uma coluna chamada "Telefone", "Celular" ou "WhatsApp".',
  CONTACT_LIMIT_EXCEEDED: 'Você chegou ao limite de contatos do seu plano. Remova contatos ou mude de plano para importar mais.',
  PRODUCT_LIMIT_EXCEEDED: 'Você chegou ao limite de produtos do seu plano de IA. Remova itens do catálogo ou mude de plano para cadastrar mais.',
  PRODUCTS_WITHOUT_IMAGE: 'O carrossel só funciona quando todos os produtos têm foto. Adicione uma foto aos que estão sem e tente de novo.',
  IMAGE_TOO_LARGE: 'A imagem passa de 2 MB. Use uma imagem menor e tente de novo.',
  INVALID_IMAGE: 'Não conseguimos abrir esta imagem. Envie uma foto em JPG, PNG, WEBP ou GIF.',
  PRODUCT_NOT_FOUND: 'Não encontramos este produto no catálogo. Ele pode ter sido excluído.',
  IMPORT_FILE_EMPTY: 'A planilha enviada está vazia. Preencha os dados e envie de novo.',
  IMPORT_FILE_TOO_LARGE: 'A planilha passa de 6 MB. Divida em arquivos menores e envie de novo.',
  IMPORT_FILE_NOT_XLSX: 'Não reconhecemos este arquivo. Envie uma planilha .xlsx, .xlsm ou .csv.',
  IMPORT_FILE_LEGACY_XLS: 'Arquivos .xls antigos não são aceitos. Abra no Excel, salve como .xlsx e envie de novo.',
  IMPORT_FILE_CORRUPTED: 'Não foi possível abrir a planilha porque o arquivo parece danificado. Salve de novo e envie outra vez.',
  IMPORT_FILE_UNREADABLE: 'Não foi possível ler a planilha. Confira se o arquivo está no formato certo e tente de novo.',
  IMPORT_SHEET_NOT_FOUND: 'Não encontramos nenhuma aba com dados na planilha. Confira o arquivo e envie de novo.',
  IMPORT_NAME_COLUMN_NOT_FOUND: 'Não encontramos a coluna de nome do produto. A planilha precisa ter uma coluna chamada "Nome" ou "Produto".',
  AI_CHANNEL_LIMIT_EXCEEDED: 'Você chegou ao limite de conexões com IA do seu plano de IA. Desligue a IA em outra conexão ou mude de plano de IA para ligar mais.',
  AI_PLAN_REQUIRED: 'Para ligar a IA, você precisa de um plano de IA ativo. Contrate um plano de IA e tente de novo.',
  AI_CHANNEL_IN_OTHER_PROFILE: 'Esta conexão já está ligada em outro perfil de IA. Desligue lá antes de ligar aqui.',
  AI_PROFILE_LIMIT_EXCEEDED: 'Você chegou ao limite de perfis de IA do seu plano. Exclua um perfil ou mude de plano de IA para criar mais.',
  AI_PROFILE_NOT_FOUND: 'Não encontramos este perfil de IA. Ele pode ter sido excluído.',
  AI_PROFILE_LAST_ONE: 'Você precisa manter pelo menos um perfil de IA. Crie outro antes de excluir este.',
  CUSTOM_RULES_LIMIT_EXCEEDED: 'As regras personalizadas passaram do limite de letras do seu plano de IA. Encurte o texto antes de salvar.',
  SCHEDULING_QUERY_NOT_ALLOWED: 'Seu plano de IA não deixa a IA consultar os horários livres. Mude de plano de IA para liberar.',
  SCHEDULING_BOOKING_NOT_ALLOWED: 'Seu plano de IA não deixa a IA marcar horários. Mude de plano de IA para liberar.',
  WEBHOOK_SIGNATURE_INVALID: 'Recebemos um aviso que não pôde ser confirmado. Confira se a integração com a plataforma de vendas foi configurada do jeito certo.',
  WEBHOOK_VERIFICATION_FAILED: 'Não foi possível confirmar a ligação com a outra plataforma. Confira os dados da integração e tente de novo.',
  NETWORK_ERROR: 'Não conseguimos falar com o Synq. Confira sua internet e tente de novo.',
  UNKNOWN: 'Algo deu errado. Tente de novo em alguns instantes.',
  WA_OFFICIAL_NOT_CONFIGURED: 'O WhatsApp Oficial ainda não está disponível na sua conta. Fale com o suporte para liberar.',
  WA_SIGNUP_CODE_EXCHANGE_FAILED: 'Não foi possível concluir a conexão com a Meta. Comece de novo pelo botão de conectar.',
  WA_WABA_NOT_FOUND: 'Nenhuma conta do WhatsApp Business foi escolhida durante a conexão. Refaça o processo e selecione uma conta.',
  WA_WEBHOOK_SUBSCRIBE_FAILED: 'O número foi conectado, mas não conseguimos ligar o recebimento de mensagens. Tente de novo em alguns instantes.',
  WA_PHONE_NUMBERS_FAILED: 'Não foi possível carregar os números da sua conta do WhatsApp Business. Tente de novo em alguns instantes.',
  WA_NO_PHONE_NUMBERS: 'Sua conta do WhatsApp Business ainda não tem números cadastrados. Cadastre um número na Meta e tente de novo.',
  WA_PHONE_NUMBER_NOT_FOUND: 'Não encontramos o número escolhido na sua conta do WhatsApp Business. Refaça a conexão e escolha outro número.',
  WA_CHANNEL_ALREADY_CONNECTED: 'Este número já está conectado na sua conta.',
  WA_PHONE_IN_USE_BY_OTHER_WORKSPACE: 'Este número já está conectado em outra conta do Synq. Desconecte de lá antes de conectar aqui.',
  WA_HEALTH_SYNC_FAILED: 'Não foi possível atualizar as informações do seu número oficial. Tente de novo em alguns instantes.',
  WA_OUTSIDE_SERVICE_WINDOW: 'Este cliente não fala com você há mais de 24h. Para chamar de novo, use um modelo aprovado.',
  WA_TEMPLATE_NOT_FOUND: 'Não encontramos este modelo de mensagem. Ele pode ter sido excluído.',
  WA_TEMPLATE_NOT_APPROVED: 'Este modelo de mensagem ainda não foi aprovado pela Meta. Espere a aprovação para usá-lo.',
  WA_TEMPLATE_ALREADY_EXISTS: 'Já existe um modelo de mensagem com este nome e idioma neste número. Escolha outro nome.',
  WA_TEMPLATE_INVALID_NAME: 'Nome inválido. Use só letras minúsculas sem acento, números e _ no lugar dos espaços. Exemplo: boas_vindas.',
  WA_TEMPLATE_NOT_EDITABLE: 'Este modelo de mensagem não pode ser editado na situação atual. Se precisar mudar o texto, crie um modelo novo.',
  WA_TEMPLATE_NOT_SYNCED: 'Este modelo de mensagem ainda não chegou à Meta. Espere alguns minutos e tente de novo.',
  WA_TEMPLATE_CREATE_FAILED: 'A Meta não recebeu o modelo de mensagem. Tente de novo em alguns instantes.',
  WA_TEMPLATE_UPDATE_FAILED: 'A Meta não recebeu as mudanças do modelo de mensagem. Tente de novo em alguns instantes.',
  WA_TEMPLATE_HEADER_UPLOAD_FAILED: 'Não foi possível enviar a imagem ou o arquivo do topo do modelo. Tente de novo ou escolha outro arquivo.',
  WA_TEMPLATE_REQUIRED_FOR_OFFICIAL: 'Campanhas pelo WhatsApp Oficial precisam de um modelo de mensagem aprovado pela Meta. Escolha um modelo aprovado.',
  WA_TEMPLATE_ONLY_FOR_OFFICIAL_CHANNELS: 'Modelos de mensagem da Meta só funcionam em números do WhatsApp Oficial. Escolha um número oficial.',
  WA_TEMPLATE_CHANNEL_MISMATCH: 'O modelo de mensagem escolhido é de outro número. Escolha um modelo do número selecionado.',
  CAMPAIGN_MIXED_CHANNEL_TYPES: 'Não dá para misturar números do WhatsApp Oficial com outros canais na mesma campanha. Crie uma campanha separada para cada tipo.',
  WA_MARKETING_OPT_OUT: 'Este contato pediu para não receber mensagens de promoção, por isso o envio foi bloqueado.',
  WA_MARKETING_LIMIT_REACHED: 'A Meta pausou por enquanto o envio de promoções para este contato. Tente de novo mais tarde.',
  WA_BILLING_ISSUE: 'Há um problema com a forma de pagamento da sua conta do WhatsApp Business na Meta. Confira o cartão cadastrado lá e tente de novo.',
  WA_RATE_LIMITED: 'Foram muitos envios em pouco tempo e a Meta pausou por alguns instantes. Tente de novo daqui a pouco.',
  CONTACT_WITHOUT_PHONE: 'Este contato não tem telefone cadastrado. Adicione o telefone e tente de novo.',
  RECIPIENT_REQUIRED: 'Escolha um contato ou digite o telefone de quem vai receber.',
  INVALID_PHONE: 'Telefone inválido. Digite o número com DDD, por exemplo: (11) 99999-9999.',
  AUTOMATION_DRAFT_FAILED: 'Não conseguimos montar a automação a partir do seu texto. Tente descrever de outro jeito, dizendo onde a pessoa vai escrever (comentário, live ou mensagem) e o que ela deve receber.',
  AUTOMATION_DRAFT_RATE_LIMITED: 'Você fez muitos pedidos seguidos. Aguarde alguns minutos e tente de novo.',
  AI_SIMULATION_NEEDS_CUSTOMER_MESSAGE: 'Escreva uma mensagem como se fosse o cliente para a IA responder.',
  AI_SIMULATION_UNAVAILABLE: 'A IA não conseguiu responder agora. Tente de novo em instantes.',
  AI_SIMULATION_RATE_LIMITED: 'Você fez muitos testes seguidos. Espere alguns minutos e tente de novo.',
  NO_SUBSCRIPTION: 'Sua conta ainda não tem um plano ativo. Escolha um plano para continuar usando o Synq.',
  SUBSCRIPTION_INACTIVE: 'Seu plano não está ativo. Renove ou escolha um plano para continuar usando o Synq.',
  CART_RECOVERY_INTEGRATION_LIMIT_EXCEEDED: 'Você chegou ao limite de lojas conectadas na Recuperação do seu plano. Mude de plano para conectar mais.',
  CHANNEL_TYPE_MISMATCH: 'O número ou a conta escolhida não combina com o tipo de envio. Escolha outra conexão.',
  INTEGRATION_NOT_FOUND: 'Não encontramos esta conexão com a loja. Ela pode ter sido removida. Atualize a página e tente de novo.',
  CART_NOT_FOUND: 'Não encontramos este carrinho. Atualize a página e tente de novo.',
};
export function getErrorMessage(reason?: string): string {
  if (!reason)
    return ERROR_MESSAGES.UNKNOWN;
  return ERROR_MESSAGES[reason as ErrorReason] || ERROR_MESSAGES.UNKNOWN;
}
