export type ErrorReason = 'UNAUTHORIZED' | 'TOKEN_MISSING' | 'TOKEN_INVALID' | 'TOKEN_EXPIRED' | 'FORBIDDEN' | 'EMAIL_ALREADY_EXISTS' | 'INVALID_CREDENTIALS' | 'USER_NOT_FOUND' | 'USER_WITHOUT_WORKSPACE' | 'NOT_FOUND' | 'VALIDATION_ERROR' | 'INTERNAL_ERROR' | 'CHANNEL_NOT_FOUND' | 'CHANNEL_NOT_CONNECTED' | 'CHANNEL_PROVIDER_MISMATCH' | 'CHANNEL_MISSING_CREDENTIALS' | 'CHANNEL_DELETE_FAILED' | 'CHANNEL_NOT_INSTAGRAM' | 'INSTAGRAM_TOKEN_EXPIRED' | 'INSTAGRAM_SEND_FAILED' | 'INSTAGRAM_OPTIN_SEND_FAILED' | 'INSTAGRAM_CONVERSATIONS_FAILED' | 'INSTAGRAM_SYNC_FAILED' | 'INSTAGRAM_CONNECT_FAILED' | 'INSTAGRAM_OAUTH_MISSING_PARAMS' | 'INSTAGRAM_INSTANCE_LIMIT_EXCEEDED' | 'INSTANCE_LIMIT_EXCEEDED' | 'RECURRING_NOTIFICATION_TOKEN_INVALID' | 'RECURRING_NOTIFICATION_TOKEN_EXPIRED' | 'NO_RECURRING_OPTIN' | 'WHATSAPP_ENV_MISSING' | 'WHATSAPP_CONNECT_FAILED' | 'WHATSAPP_STATUS_FAILED' | 'WHATSAPP_QR_FAILED' | 'WHATSAPP_DISCONNECT_FAILED' | 'WHATSAPP_WEBHOOK_CONFIG_FAILED' | 'WHATSAPP_SEND_FAILED' | 'WHATSAPP_DELETE_MSG_FAILED' | 'WHATSAPP_MARK_READ_FAILED' | 'WHATSAPP_LIST_CONTACTS_FAILED' | 'WHATSAPP_LIST_GROUPS_FAILED' | 'WHATSAPP_SYNC_FAILED' | 'WHATSAPP_INSTANCE_LIMIT_EXCEEDED' | 'CONTACT_NOT_FOUND' | 'CONTACT_IDENTITY_MISSING' | 'CONTACT_INVALID_PHONE' | 'CONTACT_SEND_FAILED' | 'GROUP_NOT_FOUND' | 'GROUP_NOT_MANUAL' | 'GROUP_CONTACTS_LIMIT_EXCEEDED' | 'CAMPAIGN_NOT_FOUND' | 'CAMPAIGN_NO_CONTACTS' | 'CAMPAIGN_RUN_FAILED' | 'CAMPAIGN_LIMIT_EXCEEDED' | 'CAMPAIGN_CONTACTS_LIMIT_EXCEEDED' | 'AUTO_REPLY_NOT_FOUND' | 'AUTO_REPLY_CREATE_FAILED' | 'AUTO_REPLY_UPDATE_FAILED' | 'AUTO_REPLY_DELETE_FAILED' | 'AUTO_REPLY_TOGGLE_FAILED' | 'AUTO_REPLY_LIMIT_EXCEEDED' | 'COMMENT_AUTOMATION_LIMIT_EXCEEDED' | 'AI_CHANNEL_LIMIT_EXCEEDED' | 'AI_PLAN_REQUIRED' | 'SCHEDULING_QUERY_NOT_ALLOWED' | 'SCHEDULING_BOOKING_NOT_ALLOWED' | 'WEBHOOK_SIGNATURE_INVALID' | 'WEBHOOK_VERIFICATION_FAILED' | 'NETWORK_ERROR' | 'UNKNOWN' | 'WA_OFFICIAL_NOT_CONFIGURED' | 'WA_SIGNUP_CODE_EXCHANGE_FAILED' | 'WA_WABA_NOT_FOUND' | 'WA_WEBHOOK_SUBSCRIBE_FAILED' | 'WA_PHONE_NUMBERS_FAILED' | 'WA_NO_PHONE_NUMBERS' | 'WA_PHONE_NUMBER_NOT_FOUND' | 'WA_CHANNEL_ALREADY_CONNECTED' | 'WA_PHONE_IN_USE_BY_OTHER_WORKSPACE' | 'WA_HEALTH_SYNC_FAILED' | 'WA_OUTSIDE_SERVICE_WINDOW' | 'WA_TEMPLATE_NOT_FOUND' | 'WA_TEMPLATE_NOT_APPROVED' | 'WA_TEMPLATE_ALREADY_EXISTS' | 'WA_TEMPLATE_INVALID_NAME' | 'WA_TEMPLATE_NOT_EDITABLE' | 'WA_TEMPLATE_NOT_SYNCED' | 'WA_TEMPLATE_CREATE_FAILED' | 'WA_TEMPLATE_UPDATE_FAILED' | 'WA_TEMPLATE_HEADER_UPLOAD_FAILED' | 'WA_TEMPLATE_REQUIRED_FOR_OFFICIAL' | 'WA_TEMPLATE_ONLY_FOR_OFFICIAL_CHANNELS' | 'WA_TEMPLATE_CHANNEL_MISMATCH' | 'CAMPAIGN_MIXED_CHANNEL_TYPES' | 'WA_MARKETING_OPT_OUT' | 'WA_MARKETING_LIMIT_REACHED' | 'WA_BILLING_ISSUE' | 'WA_RATE_LIMITED' | 'CONTACT_WITHOUT_PHONE' | 'RECIPIENT_REQUIRED' | 'INVALID_PHONE';
export const ERROR_MESSAGES: Record<ErrorReason, string> = {
  UNAUTHORIZED: 'Sessao expirada. Faca login novamente.',
  TOKEN_MISSING: 'Sessao expirada. Faca login novamente.',
  TOKEN_INVALID: 'Sessao invalida. Faca login novamente.',
  TOKEN_EXPIRED: 'Sessao expirada. Faca login novamente.',
  FORBIDDEN: 'Voce nao tem permissao para realizar esta acao.',
  EMAIL_ALREADY_EXISTS: 'Este e-mail ja esta cadastrado.',
  INVALID_CREDENTIALS: 'E-mail ou senha incorretos.',
  USER_NOT_FOUND: 'Usuario nao encontrado.',
  USER_WITHOUT_WORKSPACE: 'Usuario nao pertence a nenhum workspace.',
  NOT_FOUND: 'Recurso nao encontrado.',
  VALIDATION_ERROR: 'Dados invalidos. Verifique os campos informados.',
  INTERNAL_ERROR: 'Erro interno do servidor. Tente novamente mais tarde.',
  CHANNEL_NOT_FOUND: 'Canal nao encontrado.',
  CHANNEL_NOT_CONNECTED: 'Canal nao esta conectado.',
  CHANNEL_PROVIDER_MISMATCH: 'Provedor do canal incompativel.',
  CHANNEL_MISSING_CREDENTIALS: 'Credenciais do canal ausentes.',
  CHANNEL_DELETE_FAILED: 'Falha ao deletar canal.',
  CHANNEL_NOT_INSTAGRAM: 'Este recurso só funciona com canais Instagram.',
  INSTAGRAM_TOKEN_EXPIRED: 'Token do Instagram expirado. Reconecte a conta.',
  INSTAGRAM_SEND_FAILED: 'Falha ao enviar mensagem no Instagram.',
  INSTAGRAM_OPTIN_SEND_FAILED: 'Falha ao enviar solicitacao de opt-in.',
  INSTAGRAM_CONVERSATIONS_FAILED: 'Falha ao carregar conversas do Instagram.',
  INSTAGRAM_SYNC_FAILED: 'Falha ao sincronizar contatos do Instagram.',
  INSTAGRAM_CONNECT_FAILED: 'Falha ao conectar conta do Instagram.',
  INSTAGRAM_OAUTH_MISSING_PARAMS: 'Parametros de autenticacao do Instagram ausentes.',
  INSTAGRAM_INSTANCE_LIMIT_EXCEEDED: 'Limite de contas Instagram atingido. Remova uma conta existente para adicionar outra.',
  INSTANCE_LIMIT_EXCEEDED: 'Limite de canais do seu plano atingido (somando WhatsApp e Instagram). Remova um canal existente ou adicione uma instância extra para conectar outro.',
  RECURRING_NOTIFICATION_TOKEN_INVALID: 'Token de notificacao recorrente invalido.',
  RECURRING_NOTIFICATION_TOKEN_EXPIRED: 'Token de notificacao recorrente expirado.',
  NO_RECURRING_OPTIN: 'Contato nao aceitou receber notificacoes recorrentes.',
  WHATSAPP_ENV_MISSING: 'Configuracao do WhatsApp ausente no servidor.',
  WHATSAPP_CONNECT_FAILED: 'Falha ao conectar WhatsApp.',
  WHATSAPP_STATUS_FAILED: 'Falha ao obter status do WhatsApp.',
  WHATSAPP_QR_FAILED: 'Falha ao obter QR code do WhatsApp.',
  WHATSAPP_DISCONNECT_FAILED: 'Falha ao desconectar WhatsApp.',
  WHATSAPP_WEBHOOK_CONFIG_FAILED: 'Falha ao configurar webhooks do WhatsApp.',
  WHATSAPP_SEND_FAILED: 'Falha ao enviar mensagem no WhatsApp.',
  WHATSAPP_DELETE_MSG_FAILED: 'Falha ao deletar mensagem no WhatsApp.',
  WHATSAPP_MARK_READ_FAILED: 'Falha ao marcar como lido no WhatsApp.',
  WHATSAPP_LIST_CONTACTS_FAILED: 'Falha ao listar contatos do WhatsApp.',
  WHATSAPP_LIST_GROUPS_FAILED: 'Falha ao listar grupos do WhatsApp.',
  WHATSAPP_SYNC_FAILED: 'Falha ao sincronizar contatos do WhatsApp.',
  WHATSAPP_INSTANCE_LIMIT_EXCEEDED: 'Limite de instancias WhatsApp atingido. Remova uma instancia existente para adicionar outra.',
  CONTACT_NOT_FOUND: 'Contato nao encontrado.',
  CONTACT_IDENTITY_MISSING: 'Contato nao possui identidade neste canal.',
  CONTACT_INVALID_PHONE: 'Telefone do contato invalido.',
  CONTACT_SEND_FAILED: 'Falha ao enviar mensagem para o contato.',
  GROUP_NOT_FOUND: 'Grupo nao encontrado.',
  GROUP_NOT_MANUAL: 'Operacao disponivel apenas para grupos manuais.',
  GROUP_CONTACTS_LIMIT_EXCEEDED: 'Limite de contatos por grupo atingido. Maximo permitido: 250 contatos.',
  CAMPAIGN_NOT_FOUND: 'Campanha nao encontrada.',
  CAMPAIGN_NO_CONTACTS: 'Campanha nao possui contatos.',
  CAMPAIGN_RUN_FAILED: 'Falha ao executar campanha.',
  CAMPAIGN_LIMIT_EXCEEDED: 'Limite de campanhas atingido. Voce ja possui o maximo de campanhas permitidas no seu plano. Exclua uma campanha existente para criar uma nova.',
  CAMPAIGN_CONTACTS_LIMIT_EXCEEDED: 'Limite de contatos por campanha atingido. Maximo permitido: 250 contatos.',
  AUTO_REPLY_NOT_FOUND: 'Resposta automatica nao encontrada.',
  AUTO_REPLY_CREATE_FAILED: 'Falha ao criar resposta automatica.',
  AUTO_REPLY_UPDATE_FAILED: 'Falha ao atualizar resposta automatica.',
  AUTO_REPLY_DELETE_FAILED: 'Falha ao deletar resposta automatica.',
  AUTO_REPLY_TOGGLE_FAILED: 'Falha ao alternar resposta automatica.',
  AUTO_REPLY_LIMIT_EXCEEDED: 'Você atingiu o limite de respostas automáticas do seu plano. Exclua uma resposta existente ou faça upgrade do plano para criar uma nova.',
  COMMENT_AUTOMATION_LIMIT_EXCEEDED: 'Você atingiu o limite de automações de comentário do seu plano. Exclua uma automação existente ou faça upgrade do plano para criar uma nova.',
  AI_CHANNEL_LIMIT_EXCEEDED: 'Você atingiu o limite de canais com IA do seu plano de IA. Desative a IA em outro canal ou faça upgrade do plano de IA para ativar mais.',
  AI_PLAN_REQUIRED: 'Você precisa de um plano de IA ativo para ativar a IA em um canal.',
  SCHEDULING_QUERY_NOT_ALLOWED: 'Seu plano de IA atual não permite consulta de disponibilidade. Faça upgrade do plano de IA para liberar este recurso.',
  SCHEDULING_BOOKING_NOT_ALLOWED: 'Seu plano de IA atual não permite criação de agendamentos. Faça upgrade do plano de IA para liberar este recurso.',
  WEBHOOK_SIGNATURE_INVALID: 'Assinatura do webhook invalida.',
  WEBHOOK_VERIFICATION_FAILED: 'Verificacao do webhook falhou.',
  NETWORK_ERROR: 'Erro de conexao. Verifique sua internet.',
  UNKNOWN: 'Erro desconhecido. Tente novamente.',
  WA_OFFICIAL_NOT_CONFIGURED: 'A integracao com a API Oficial ainda nao foi configurada no servidor. Contate o suporte.',
  WA_SIGNUP_CODE_EXCHANGE_FAILED: 'Falha ao concluir a conexao com a Meta. Tente conectar novamente.',
  WA_WABA_NOT_FOUND: 'Nenhuma conta WhatsApp Business foi compartilhada durante a conexao. Refaca o processo selecionando uma conta.',
  WA_WEBHOOK_SUBSCRIBE_FAILED: 'Falha ao ativar o recebimento de mensagens da conta oficial. Tente novamente.',
  WA_PHONE_NUMBERS_FAILED: 'Falha ao listar os numeros da sua conta WhatsApp Business.',
  WA_NO_PHONE_NUMBERS: 'Sua conta WhatsApp Business nao possui numeros cadastrados.',
  WA_PHONE_NUMBER_NOT_FOUND: 'Numero selecionado nao encontrado na conta WhatsApp Business.',
  WA_CHANNEL_ALREADY_CONNECTED: 'Este numero ja esta conectado no seu workspace.',
  WA_PHONE_IN_USE_BY_OTHER_WORKSPACE: 'Este numero ja esta conectado em outro workspace.',
  WA_HEALTH_SYNC_FAILED: 'Falha ao atualizar as informacoes da conta oficial.',
  WA_OUTSIDE_SERVICE_WINDOW: 'A janela de atendimento de 24h deste contato esta fechada. Use um template aprovado para iniciar a conversa.',
  WA_TEMPLATE_NOT_FOUND: 'Template nao encontrado.',
  WA_TEMPLATE_NOT_APPROVED: 'Este template ainda nao foi aprovado pela Meta.',
  WA_TEMPLATE_ALREADY_EXISTS: 'Ja existe um template com este nome e idioma neste canal.',
  WA_TEMPLATE_INVALID_NAME: 'Nome invalido. Use apenas letras minusculas, numeros e underscore.',
  WA_TEMPLATE_NOT_EDITABLE: 'Este template nao pode ser editado no status atual.',
  WA_TEMPLATE_NOT_SYNCED: 'Template ainda nao sincronizado com a Meta.',
  WA_TEMPLATE_CREATE_FAILED: 'Falha ao criar o template na Meta. Tente novamente.',
  WA_TEMPLATE_UPDATE_FAILED: 'Falha ao atualizar o template na Meta. Tente novamente.',
  WA_TEMPLATE_HEADER_UPLOAD_FAILED: 'Falha ao enviar a midia do cabecalho do template.',
  WA_TEMPLATE_REQUIRED_FOR_OFFICIAL: 'Campanhas pela API Oficial exigem um template aprovado pela Meta.',
  WA_TEMPLATE_ONLY_FOR_OFFICIAL_CHANNELS: 'Templates da Meta so podem ser usados em canais da API Oficial.',
  WA_TEMPLATE_CHANNEL_MISMATCH: 'O template selecionado nao pertence ao canal escolhido.',
  CAMPAIGN_MIXED_CHANNEL_TYPES: 'Nao e possivel misturar canais oficiais e nao oficiais na mesma campanha. Crie campanhas separadas.',
  WA_MARKETING_OPT_OUT: 'Este contato optou por nao receber mensagens de marketing.',
  WA_MARKETING_LIMIT_REACHED: 'A Meta limitou o envio de marketing para este contato no momento. Tente mais tarde.',
  WA_BILLING_ISSUE: 'Problema de cobranca na sua conta Meta. Verifique o metodo de pagamento da sua WABA.',
  WA_RATE_LIMITED: 'Limite de envio da Meta atingido momentaneamente. Tente novamente em instantes.',
  CONTACT_WITHOUT_PHONE: 'Este contato nao possui telefone neste canal.',
  RECIPIENT_REQUIRED: 'Informe um contato ou telefone de destino.',
  INVALID_PHONE: 'Telefone invalido.',
};
export function getErrorMessage(reason?: string): string {
  if (!reason)
    return ERROR_MESSAGES.UNKNOWN;
  return ERROR_MESSAGES[reason as ErrorReason] || ERROR_MESSAGES.UNKNOWN;
}
